linters-settings:
  lll:
    line-length: 160
  dogsled:
    max-blank-identifiers: 3
  goimports:
    local-prefixes: github.com/michurin/jsonpainter
  funlen:
    lines: 90
    statements: 60
  cyclop:
    max-complexity: 20
linters:
  enable-all: true
  disable:
    - depguard
    - gochecknoglobals
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
      # deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
