linters-settings:
  lll:
    line-length: 160
  dogsled:
    max-blank-identifiers: 3
  goimports:
    local-prefixes: github.com/michurin/jsonpainter
  funlen:
    lines: 80
    statements: 60
  cyclop:
    max-complexity: 20
linters:
  enable-all: true
  disable:
    - gci
    - gochecknoglobals
    - nlreturn
    - paralleltest
    - varnamelen
    - wsl
      # deprecated
    - golint
    - scopelint
    - interfacer
    - maligned
