---
name: build # this string appears on badge
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      -
        name: "Run linter"
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53 # Required. Must be specified without patch version
      -
        name: "Run coverage"
        run: "go test -v -race -coverprofile=coverage.txt -covermode=atomic ."
      -
        name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          verbose: true
